/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Stock;

import Bienvenido.Menu;
import CargaDescarga.CargaDePedido;
import CargaDescarga.ImprimirPedido;
import FNC.ConsultasDePaginado;
import FNC.Funciones;
import static FNC.Funciones.isNumeric;
import FNC.Paginado;
import static Stock.ConsultasStock.numero;
import Venta.Vta;
import static java.awt.EventQueue.invokeLater;
import static java.awt.event.KeyEvent.VK_ESCAPE;
import static java.awt.event.KeyEvent.VK_F1;
import static java.lang.Integer.valueOf;
import java.sql.SQLException;
import java.util.Vector;
import static java.util.logging.Level.SEVERE;
import static java.util.logging.Logger.getLogger;
import javax.swing.ImageIcon;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import static javax.swing.JOptionPane.YES_OPTION;
import static javax.swing.JOptionPane.showConfirmDialog;
import static javax.swing.JOptionPane.showInputDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.UIManager.getInstalledLookAndFeels;
import static javax.swing.UIManager.setLookAndFeel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Valentin
 */
public class Stok extends javax.swing.JFrame {

    /**
     * Creates new form Stok
     */
    public Vector s;
    DefaultTableModel a;
    DefaultTableModel b;
    public int llamadaV3;
    int cant = 0;

    public Stok() {
        initComponents();
        /* ConsultaInicioSesion ini = new ConsultaInicioSesion();
        String tipo = ini.guardar();
        if (tipo.equals("2")) {
            btnTruncate.setVisible(false);
        }*/

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        TxtBuscar = new javax.swing.JTextField();
        TipoBusqueda = new javax.swing.JComboBox();
        btnBuscar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        VolverM1 = new javax.swing.JButton();
        botonPedido = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblStockBajo = new javax.swing.JTable();
        modProduc = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabla2 = new javax.swing.JTable();
        btnLimpiar = new javax.swing.JButton();
        cmbAlBa = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        btnModTabla = new javax.swing.JButton();
        cmbPag = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnConfigStock = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        btnrefrescartabla = new javax.swing.JButton();
        imglabel = new javax.swing.JLabel();
        filCant = new javax.swing.JComboBox();
        TxtBuscar1 = new javax.swing.JTextField();
        btnBuscarCant = new javax.swing.JButton();
        TxtBuscar2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnProductos = new javax.swing.JButton();
        VolverM2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgregarProd = new javax.swing.JTable();
        btnFilas = new javax.swing.JButton();
        nroFilas = new javax.swing.JComboBox<>();
        btnEliminar = new javax.swing.JButton();
        btnEliminarTodo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnModProv = new javax.swing.JButton();
        btnElimProv = new javax.swing.JButton();
        btnLimTbl = new javax.swing.JButton();
        VolverM3 = new javax.swing.JButton();
        btnBuscarProv = new javax.swing.JButton();
        txtBuscarProv = new javax.swing.JTextField();
        cmbFiltro = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        btnTruncate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProveedor = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnAgregarFila = new javax.swing.JButton();
        btnEliminarFila = new javax.swing.JButton();
        btnLimpiarTabla = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblAgregarProv = new javax.swing.JTable();
        VolverM4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stock");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(new ImageIcon(getClass().getResource("/Logo.png")).getImage());
        setMinimumSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jTabbedPane3.setMinimumSize(new java.awt.Dimension(800, 600));
        jTabbedPane3.setPreferredSize(new java.awt.Dimension(800, 600));
        jTabbedPane3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTabbedPane3KeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(100, 183, 100));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        TipoBusqueda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Descripción", "IDProducto", "PrecioSIVA", "PrecioCIVA" }));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Buscar por:");

        VolverM1.setText("Volver Menu");
        VolverM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverM1ActionPerformed(evt);
            }
        });
        VolverM1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VolverM1KeyPressed(evt);
            }
        });

        botonPedido.setText("Pedido de productos");
        botonPedido.setToolTipText("Lleva a ventana para realizar un pedido");
        botonPedido.setVisible(true);
        botonPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPedidoActionPerformed(evt);
            }
        });

        tblStockBajo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Bajo stock mercadería", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStockBajo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblStockBajoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane5.setViewportView(tblStockBajo);
        if (tblStockBajo.getColumnModel().getColumnCount() > 0) {
            tblStockBajo.getColumnModel().getColumn(0).setResizable(false);
            tblStockBajo.getColumnModel().getColumn(0).setPreferredWidth(150);
            tblStockBajo.getColumnModel().getColumn(1).setResizable(false);
        }

        modProduc.setText("Modificar Alta/Baja");
        modProduc.setToolTipText("Modifica alta/baja productos (Alta= toma el producto, Baja= No toma el producto)");
        modProduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modProducActionPerformed(evt);
            }
        });

        Tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "IDProducto", "Descripcion", "Cantidad", "PrecioS/IVA", "PrecioC/IVA", "Oferta", "Alta/Baja"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tabla2.getTableHeader().setReorderingAllowed(false);
        Tabla2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Tabla2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Tabla2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Tabla2KeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(Tabla2);
        if (Tabla2.getColumnModel().getColumnCount() > 0) {
            Tabla2.getColumnModel().getColumn(0).setResizable(false);
            Tabla2.getColumnModel().getColumn(1).setResizable(false);
            Tabla2.getColumnModel().getColumn(1).setPreferredWidth(150);
            Tabla2.getColumnModel().getColumn(2).setResizable(false);
            Tabla2.getColumnModel().getColumn(3).setResizable(false);
            Tabla2.getColumnModel().getColumn(4).setResizable(false);
            Tabla2.getColumnModel().getColumn(5).setResizable(false);
            Tabla2.getColumnModel().getColumn(6).setResizable(false);
        }

        btnLimpiar.setText("Limpiar campos");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        cmbAlBa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar:", "Alta", "Baja" }));
        cmbAlBa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel7.setText("Alta/Baja Producto");

        btnModTabla.setText("Modificar tabla");
        btnModTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModTablaActionPerformed(evt);
            }
        });

        cmbPag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPagActionPerformed(evt);
            }
        });

        jLabel1.setText("Pagina:");

        jLabel3.setText("de");

        jLabel4.setText("jLabel4");
        jLabel4.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel4AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btnConfigStock.setText("Modificar stock bajo");
        btnConfigStock.setToolTipText("Boton que establece el numero para la cantidad de stock bajo");
        btnConfigStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigStockActionPerformed(evt);
            }
        });

        txtArea.setEditable(false);
        txtArea.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.activeBorderColor"));
        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        txtArea.setRows(5);
        txtArea.setText("Cantidad de stock\nbajo establecida\nen = Cantidad ");
        txtArea.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtAreaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane4.setViewportView(txtArea);

        jButton1.setText("Cargar pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnrefrescartabla.setText("Refresca stock");
        btnrefrescartabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefrescartablaActionPerformed(evt);
            }
        });

        imglabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo58x125.png"))); // NOI18N
        imglabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                imglabelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        filCant.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cantidad", "PrecioSIVA", "PrecioCIVA" }));

        TxtBuscar1.setToolTipText("Precio o cant inicial");

        btnBuscarCant.setText("Buscar");
        btnBuscarCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCantActionPerformed(evt);
            }
        });

        TxtBuscar2.setToolTipText("Precio o cant final");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(modProduc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbAlBa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(77, 77, 77)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(imglabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnConfigStock)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TipoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnrefrescartabla)
                                .addGap(40, 40, 40)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnModTabla)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar)
                                .addGap(56, 56, 56)
                                .addComponent(VolverM1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1)
                                .addGap(4, 4, 4)
                                .addComponent(cmbPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(filCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(TxtBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TxtBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel3)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addComponent(btnBuscarCant)))))
                .addGap(45, 45, 45))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(imglabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(botonPedido)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbAlBa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modProduc)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnConfigStock)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TipoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar)
                            .addComponent(filCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarCant))))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnModTabla)
                        .addComponent(btnLimpiar)
                        .addComponent(btnrefrescartabla))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(VolverM1)
                        .addComponent(jLabel1)
                        .addComponent(cmbPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)))
                .addGap(23, 23, 23))
        );

        jTabbedPane3.addTab("Stock", jPanel1);

        jPanel2.setBackground(new java.awt.Color(100, 183, 100));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel2KeyPressed(evt);
            }
        });

        btnProductos.setText("Agregar producto");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        VolverM2.setText("Volver Menu");
        VolverM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverM2ActionPerformed(evt);
            }
        });
        VolverM2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VolverM2KeyPressed(evt);
            }
        });

        tblAgregarProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Titlo5"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        //getTableHeader().setReorderingAllowed(false); Hace que no se mueva la
        //Cabecera del jtable
        tblAgregarProd.getTableHeader().setReorderingAllowed(false);
        tblAgregarProd.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblAgregarProdAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblAgregarProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblAgregarProdKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblAgregarProd);

        btnFilas.setText("Agregar filas");
        btnFilas.setToolTipText("Agrega el numero de filas seleccionado");
        btnFilas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFilasMouseClicked(evt);
            }
        });
        btnFilas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilasActionPerformed(evt);
            }
        });

        nroFilas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        nroFilas.setToolTipText("Numero de filas");

        btnEliminar.setText("Eliminar filas");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEliminarTodo.setText("Limpiar tabla");
        btnEliminarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnProductos)
                .addGap(10, 10, 10)
                .addComponent(btnFilas)
                .addGap(6, 6, 6)
                .addComponent(nroFilas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnEliminar)
                .addGap(6, 6, 6)
                .addComponent(btnEliminarTodo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(635, Short.MAX_VALUE)
                .addComponent(VolverM2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProductos)
                    .addComponent(btnFilas)
                    .addComponent(nroFilas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar)
                    .addComponent(btnEliminarTodo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                .addComponent(VolverM2)
                .addGap(30, 30, 30))
        );

        jTabbedPane3.addTab("Agregar producto", jPanel2);

        jPanel3.setBackground(new java.awt.Color(100, 183, 100));
        jPanel3.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel3AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        btnModProv.setText("Modificar proveedor");
        btnModProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModProvActionPerformed(evt);
            }
        });

        btnElimProv.setText("Eliminar proveedor");
        btnElimProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimProvActionPerformed(evt);
            }
        });

        btnLimTbl.setText("Limpiar tabla");
        btnLimTbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimTblActionPerformed(evt);
            }
        });

        VolverM3.setText("Volver Menu");
        VolverM3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverM3ActionPerformed(evt);
            }
        });
        VolverM3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VolverM3KeyPressed(evt);
            }
        });

        btnBuscarProv.setText("Buscar");
        btnBuscarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProvActionPerformed(evt);
            }
        });

        txtBuscarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarProvActionPerformed(evt);
            }
        });

        cmbFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "Apellido" }));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Buscar por:");

        btnTruncate.setText("Eliminar registros");
        btnTruncate.setToolTipText("Este boton elimina todos los registros de Proveedores de la BD");
        btnTruncate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruncateActionPerformed(evt);
            }
        });

        tblProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        tblProveedor.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblProveedorAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblProveedorKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblProveedor);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(VolverM3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(btnModProv)
                        .addGap(6, 6, 6)
                        .addComponent(btnElimProv)
                        .addGap(6, 6, 6)
                        .addComponent(btnTruncate))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel14)
                        .addGap(4, 4, 4)
                        .addComponent(cmbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtBuscarProv, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnBuscarProv)
                        .addGap(6, 6, 6)
                        .addComponent(btnLimTbl)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModProv)
                    .addComponent(btnElimProv)
                    .addComponent(btnTruncate))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel14))
                    .addComponent(cmbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtBuscarProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscarProv)
                    .addComponent(btnLimTbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                .addComponent(VolverM3)
                .addGap(30, 30, 30))
        );

        jTabbedPane3.addTab("Proveedores", jPanel3);

        jPanel4.setBackground(new java.awt.Color(100, 183, 100));

        btnAgregar.setText("Agregar proveedor");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnAgregarFila.setText("Agregar fila");
        btnAgregarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarFilaActionPerformed(evt);
            }
        });

        btnEliminarFila.setText("Eliminar fila");
        btnEliminarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFilaActionPerformed(evt);
            }
        });

        btnLimpiarTabla.setText("Limpiar tabla");
        btnLimpiarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarTablaActionPerformed(evt);
            }
        });

        tblAgregarProv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Título 1", "Título 2", "Título 3", "Título 4", "null", "null"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblAgregarProv.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblAgregarProvAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblAgregarProv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAgregarProvMouseClicked(evt);
            }
        });
        tblAgregarProv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblAgregarProvKeyPressed(evt);
            }
        });
        jScrollPane8.setViewportView(tblAgregarProv);
        if (tblAgregarProv.getColumnModel().getColumnCount() > 0) {
            tblAgregarProv.getColumnModel().getColumn(0).setResizable(false);
            tblAgregarProv.getColumnModel().getColumn(1).setResizable(false);
            tblAgregarProv.getColumnModel().getColumn(2).setResizable(false);
            tblAgregarProv.getColumnModel().getColumn(4).setResizable(false);
            tblAgregarProv.getColumnModel().getColumn(5).setResizable(false);
        }

        VolverM4.setText("Volver Menu");
        VolverM4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverM4ActionPerformed(evt);
            }
        });
        VolverM4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VolverM4KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(VolverM4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarFila)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarFila)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiarTabla)
                        .addGap(0, 357, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnAgregarFila)
                    .addComponent(btnEliminarFila)
                    .addComponent(btnLimpiarTabla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                .addComponent(VolverM4)
                .addGap(30, 30, 30))
        );

        jTabbedPane3.addTab("Agregar Proveedor", jPanel4);

        getContentPane().add(jTabbedPane3, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        char car = evt.getKeyChar();
        if (car == VK_ESCAPE) {
            Tabla2.clearSelection();
            tblStockBajo.clearSelection();

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void jTabbedPane3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabbedPane3KeyPressed
        char car = evt.getKeyChar();
        if (car == VK_ESCAPE) {
            Tabla2.clearSelection();
            tblStockBajo.clearSelection();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane3KeyPressed

    private void txtBuscarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarProvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarProvActionPerformed

    private void btnBuscarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProvActionPerformed
        // TODO add your handling code here:
        ConsultaProveedor con = new ConsultaProveedor();
        String filtro = cmbFiltro.getSelectedItem().toString();
        String busqueda = txtBuscarProv.getText();
        con.buscarProvee(filtro, busqueda, tblProveedor);
    }//GEN-LAST:event_btnBuscarProvActionPerformed

    private void VolverM3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VolverM3KeyPressed
        // TODO add your handling code here:
        char carr = (char) evt.getKeyCode();
        if (carr == VK_F1) {
            Menu men = new Menu();
            men.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_VolverM3KeyPressed

    private void VolverM3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverM3ActionPerformed
        // TODO add your handling code here:
        Menu men = new Menu();
        men.setVisible(true);
        dispose();
    }//GEN-LAST:event_VolverM3ActionPerformed

    private void jPanel2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel2KeyPressed
        // TODO add your handling code here:
        int code = evt.getKeyCode();
        if (code == VK_ESCAPE) {
            tblAgregarProd.clearSelection();
        }

    }//GEN-LAST:event_jPanel2KeyPressed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        tblAgregarProd.clearSelection();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void btnEliminarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTodoActionPerformed
        // TODO add your handling code here:
        ModificacionJtable mod = new ModificacionJtable();
        mod.limpiarTabla(tblAgregarProd);
    }//GEN-LAST:event_btnEliminarTodoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        ModificacionJtable mod = new ModificacionJtable();

        mod.eliminarFilas(tblAgregarProd);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnFilasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilasActionPerformed
        // TODO add your handling code here:
        ModificacionJtable ag = new ModificacionJtable();

        int filas = nroFilas.getSelectedIndex();
        ag.agregarfila(tblAgregarProd, filas);
    }//GEN-LAST:event_btnFilasActionPerformed

    private void btnFilasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFilasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFilasMouseClicked

    private void tblAgregarProdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblAgregarProdKeyPressed
        // TODO add your handling code here:
        int code = evt.getKeyCode();
        if (code == VK_ESCAPE) {
            tblAgregarProd.clearSelection();
        }
    }//GEN-LAST:event_tblAgregarProdKeyPressed

    private void tblAgregarProdAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblAgregarProdAncestorAdded
        // TODO add your handling code here:
        ModificacionJtable ag = new ModificacionJtable();
        ag.modificartbl(tblAgregarProd);
    }//GEN-LAST:event_tblAgregarProdAncestorAdded

    private void VolverM2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VolverM2KeyPressed
        // TODO add your handling code here:
        char carr = (char) evt.getKeyCode();
        if (carr == VK_F1) {
            Menu men = new Menu();
            men.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_VolverM2KeyPressed

    private void VolverM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverM2ActionPerformed
        // TODO add your handling code here:
        Menu men = new Menu();
        men.setVisible(true);
        dispose();
    }//GEN-LAST:event_VolverM2ActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // TODO add your handling code here:
        ConsultasStock cons = new ConsultasStock();
        cons.agregarProducto(tblAgregarProd);
    }//GEN-LAST:event_btnProductosActionPerformed

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        char car = evt.getKeyChar();
        if (car == VK_ESCAPE) {
            Tabla2.clearSelection();
            tblStockBajo.clearSelection();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1KeyPressed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        Tabla2.clearSelection();
        tblStockBajo.clearSelection();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void btnModTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModTablaActionPerformed
        //Modifica las columnas tabla
        ConsultasStock cc = new ConsultasStock();
        cc.modificarTablaStock(Tabla2);
        cc.cargarTablaStockBajo(tblStockBajo);
    }//GEN-LAST:event_btnModTablaActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        ModificacionJtable mod = new ModificacionJtable();
        mod.limpiarTabla(Tabla2);
        cmbAlBa.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void modProducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modProducActionPerformed
        //Modifica alta y baja en los prooductos
        //getSelectedRow(); sirve para traer si se selecciono alguna fila
        DefaultTableModel model = (DefaultTableModel) Tabla2.getModel();
        int selectfila = Tabla2.getSelectedRow();
        //getRowCount(); cueta las filas
        int cantFila = Tabla2.getRowCount();
        int o = 0;
        int sor = showConfirmDialog(null, "¿Esta seguro que desea modificar los registros seleccionados?", "Pregunta", WARNING_MESSAGE);
        if (sor == YES_OPTION) {
            //Verifico que seleccione por lo menos una fila para modificar la tabla .
            if (selectfila == -1) {
                showMessageDialog(null, "Debe seleccionar aunque sea una fila a modificar", "Informacion", INFORMATION_MESSAGE);
            } else {
                //Recorro fila por fila para saber cual a sido seleccionada y cual no las seleccionadas,
                //se modifican segun el combo bbox de alta baja .
                for (int i = 0; i < cantFila; i++) {
                    Boolean fila = Tabla2.isRowSelected(i);
                    //Si la fila fue seleccionada se modificara
                    if (fila == true) {

                        Object ab = cmbAlBa.getSelectedItem();
                        //Verifico que el cmb sea distinto de Seleccionar para modificar fila.
                        if (ab != "Seleccionar:") {
                            model.setValueAt(ab, i, 6);

                        } else {
                            showMessageDialog(null, "Debe seleccionar una opcion baja o alta", "Informacion", INFORMATION_MESSAGE);
                        }
                        cmbAlBa.setSelectedIndex(0);
                    }

                }
                //Seteo el modelo a la tabla y lo envio a consultas para trabajar con BD
                ConsultasStock con = new ConsultasStock();
                Tabla2.setModel(model);

                con.modstock(Tabla2);

            }
        } else {
            showMessageDialog(null, "Registros no modificados");
        }

        ConsultasStock con = new ConsultasStock();
        con.cargarTablaStockBajo(tblStockBajo);
    }//GEN-LAST:event_modProducActionPerformed

    private void tblStockBajoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblStockBajoAncestorAdded
        // TODO add your handling code here:
        ConsultasStock conec = new ConsultasStock();

        conec.cargarTablaStockBajo(tblStockBajo);
    }//GEN-LAST:event_tblStockBajoAncestorAdded

    private void botonPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPedidoActionPerformed
        // TODO add your handling code here:
        ImprimirPedido ped = new ImprimirPedido();

        ped.setVisible(true);
    }//GEN-LAST:event_botonPedidoActionPerformed

    private void VolverM1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VolverM1KeyPressed
        // TODO add your handling code here:
        char carr = (char) evt.getKeyCode();
        if (carr == VK_F1) {
            Menu men = new Menu();
            men.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_VolverM1KeyPressed

    private void VolverM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverM1ActionPerformed
        // TODO add your handling code here:
        Menu men = new Menu();
        men.setVisible(true);
        dispose();
    }//GEN-LAST:event_VolverM1ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        //Boton buscar de lista stock
        Paginado p = new Paginado();
        ConsultasDePaginado cdp = new ConsultasDePaginado();
        //Tomo el filtro y el valor para ejecutar consulta
        String fil = TipoBusqueda.getSelectedItem().toString();
        String val = TxtBuscar.getText();
        //Genero consulta para contar los registros
        String SSQL = cdp.getsqlBuscarStok(fil, val);
        //Paso el combo y el sql para que cuente los registros y pagine el JTable
        p.contarReg(cmbPag, SSQL);
        //Instancio llamada para ejecutar sql despues de contar los registro 
        //Debe de hacerse doble consulta para paginar un JTable
        this.llamadaV3 = 1;
        //llamo al evento en cmb para que me ejecute la consulta final con los limitadores
        this.cmbPagActionPerformed(evt);
        p.setJlabelPag(jLabel4, cmbPag);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnElimProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimProvActionPerformed
        // TODO add your handling code here:
        ModiTblProveedor mod = new ModiTblProveedor();
        mod.eliminarProveedor(tblProveedor);
    }//GEN-LAST:event_btnElimProvActionPerformed

    private void btnModProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModProvActionPerformed
        // TODO add your handling code here:
        ModiTblProveedor mod = new ModiTblProveedor();
        mod.modProve(tblProveedor);
    }//GEN-LAST:event_btnModProvActionPerformed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        tblProveedor.clearSelection();
    }//GEN-LAST:event_jPanel3MouseClicked

    private void btnLimTblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimTblActionPerformed
        // TODO add your handling code here:
        ModificacionJtable mod = new ModificacionJtable();
        mod.limpiarTabla(tblProveedor);
    }//GEN-LAST:event_btnLimTblActionPerformed

    private void jPanel3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel3AncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel3AncestorAdded

    private void btnTruncateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruncateActionPerformed
        int b = showConfirmDialog(null, "¿Esta seguro que desea borrar completamente los registros de proveedores? \n"
                + " Esto producirá que se quede sin datos de los proveedores", "Información", WARNING_MESSAGE);
        if (b == YES_OPTION) {
            try {
                ConsultaProveedor ini = new ConsultaProveedor();
                ini.borrarRegistroProvee();
            } catch (SQLException ex) {
                getLogger(Stok.class.getName()).log(SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnTruncateActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        ConsultaProveedor con = new ConsultaProveedor();
        con.agregarProveedor(tblAgregarProv);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tblAgregarProvAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblAgregarProvAncestorAdded
        // TODO add your handling code here:
        ModiTblProveedor mod = new ModiTblProveedor();
        mod.modificartblprove(tblAgregarProv);
    }//GEN-LAST:event_tblAgregarProvAncestorAdded

    private void tblAgregarProvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAgregarProvMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblAgregarProvMouseClicked

    private void tblAgregarProvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblAgregarProvKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblAgregarProvKeyPressed

    private void btnAgregarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarFilaActionPerformed
        // TODO add your handling code here:
        ModiTblProveedor mod = new ModiTblProveedor();
        mod.agregarfila(tblAgregarProv);
    }//GEN-LAST:event_btnAgregarFilaActionPerformed

    private void btnEliminarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFilaActionPerformed
        // TODO add your handling code here:
        ModificacionJtable mod = new ModificacionJtable();
        mod.eliminarFilas(tblAgregarProv);
    }//GEN-LAST:event_btnEliminarFilaActionPerformed

    private void btnLimpiarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarTablaActionPerformed
        // TODO add your handling code here:
        ModificacionJtable mod = new ModificacionJtable();
        mod.limpiarTabla(tblAgregarProv);
    }//GEN-LAST:event_btnLimpiarTablaActionPerformed

    private void VolverM4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverM4ActionPerformed
        // TODO add your handling code here:
        Menu men = new Menu();
        men.setVisible(true);
        dispose();
    }//GEN-LAST:event_VolverM4ActionPerformed

    private void VolverM4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VolverM4KeyPressed
        // TODO add your handling code here:
        char carr = (char) evt.getKeyCode();
        if (carr == VK_F1) {
            Menu men = new Menu();
            men.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_VolverM4KeyPressed

    private void Tabla2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tabla2KeyPressed
        char car = evt.getKeyChar();
        if (car == VK_ESCAPE) {
            Tabla2.clearSelection();
            tblStockBajo.clearSelection();

        }
    }//GEN-LAST:event_Tabla2KeyPressed

    private void cmbPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPagActionPerformed
        // TODO add your handling code here:
        //Creo objeto paginado donde poseo la crecion de jtable por pagina
        Paginado p = new Paginado();
        //Creo vriable result en donde almacenare los dos numeros para limitar la consulta SQL
        int[] result = {0, 0};
        //Instancio la variable con los numeros a limitar
        result = p.cmbDePaginas(cmbPag);
        //Genero el if para depender de que llamada se realiza
        if (this.llamadaV3 == 0) {
            ConsultasStock con = new ConsultasStock();
            con.rellenarStock(Tabla2, result);
        } else if (this.llamadaV3 == 1) {
            ConsultasStock conec = new ConsultasStock();
            String Filtro = TipoBusqueda.getSelectedItem().toString();
            String Busqueda = TxtBuscar.getText();
            conec.cargarTablaStockBajo(tblStockBajo);
            conec.buscarStock(Filtro, Busqueda, Tabla2, result);

        } else if (this.llamadaV3 == 2) {
            ConsultasStock con = new ConsultasStock();
            con.cargarTablaStockBajo(tblStockBajo);
            String filCantidad = filCant.getSelectedItem().toString();
            String valA = TxtBuscar1.getText();
            String valB = TxtBuscar2.getText();
            con.buscarPorCantidadPrecio(filCantidad, valA, valB, Tabla2, result);
        }
    }//GEN-LAST:event_cmbPagActionPerformed

    private void jLabel4AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel4AncestorAdded
        // TODO add your handling code here:
        Paginado p = new Paginado();
        p.setJlabelPag(jLabel4, cmbPag);
    }//GEN-LAST:event_jLabel4AncestorAdded

    private void tblProveedorAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblProveedorAncestorAdded
        // TODO add your handling code here:

        ConsultaProveedor cn = new ConsultaProveedor();
        cn.buscarProveeInstantaneamente(tblProveedor);

    }//GEN-LAST:event_tblProveedorAncestorAdded

    private void tblProveedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblProveedorKeyPressed
        // TODO add your handling code here:
        int code = evt.getKeyCode();
        if (code == VK_ESCAPE) {
            tblProveedor.clearSelection();
        }
    }//GEN-LAST:event_tblProveedorKeyPressed

    private void btnConfigStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigStockActionPerformed
        // TODO add your handling code here:
        Funciones f = new Funciones();
        ConsultasStock cn = new ConsultasStock();
        //ingresa numero de stock bajo
        String numero = showInputDialog(null, "Ingrese un número para establecer el valor de Stock bajo en el programa", "Configuración", INFORMATION_MESSAGE);
        //si es numerico se guarda y se asigna a la BD como nuevo valor
        if (isNumeric(numero) == true) {
            cn.cfgNumStock(valueOf(numero));

        } else {
            //si no es numerico no se guarda y muestra el else que es un mensaje de error
            showMessageDialog(null, "Error, usted no ha ingresado un numero !", "ERROR", ERROR_MESSAGE);
        }
        //una vez asignado el numero vuelve a cargar el jtable con el nuevo valor numerico asignado a la BD
        cn.cargarTablaStockBajo(tblStockBajo);
        //llamo a numero para obtener el valor de la cantidad de stock bajo establecida
        txtArea.setText("Cantidad de stock\nbajo establecida\nen = Cantidad (" + numero() + ")");
    }//GEN-LAST:event_btnConfigStockActionPerformed

    private void txtAreaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtAreaAncestorAdded
        // TODO add your handling code here:
        //llamo a numero para obtener el valor de la cantidad de stock bajo establecida
        ConsultasStock cs = new ConsultasStock();
        txtArea.setText("Cantidad de stock\nbajo establecida\nen = Cantidad (" + numero() + ")");
    }//GEN-LAST:event_txtAreaAncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CargaDePedido cp = new CargaDePedido();
        cp.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Tabla2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Tabla2AncestorAdded
        // TODO add your handling code here:
        Paginado p = new Paginado();
        ConsultasDePaginado cp = new ConsultasDePaginado();
        //Paso la consulta y el cmb por string para realizar el proceso de paginado del table
        //El resto funciona internamente en el metodo que esta en paginado en el paquete FNC
        String sqlNumReg = cp.getAncestorAddedTablaStock();
        p.contarReg(cmbPag, sqlNumReg);
        this.llamadaV3 = 0;

    }//GEN-LAST:event_Tabla2AncestorAdded

    private void btnrefrescartablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefrescartablaActionPerformed
        // TODO add your handling code here:
        //Uso este boton para llamarlo desde otras tablas y así refrescar tabla stock y stockBajo
        Paginado p = new Paginado();
        ConsultasDePaginado cp = new ConsultasDePaginado();
        //Paso la consulta y el cmb por string para realizar el proceso de paginado del table
        //El resto funciona internamente en el metodo que esta en paginado en el paquete FNC
        String sqlNumReg = cp.getAncestorAddedTablaStock();
        p.contarReg(cmbPag, sqlNumReg);
        this.llamadaV3 = 0;
        ConsultasStock cs = new ConsultasStock();
        cs.cargarTablaStockBajo(tblStockBajo);
    }//GEN-LAST:event_btnrefrescartablaActionPerformed

    private void imglabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_imglabelAncestorAdded

    }//GEN-LAST:event_imglabelAncestorAdded

    private void btnBuscarCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCantActionPerformed
        //Boton buscar de lista stock
        Paginado p = new Paginado();
        ConsultasDePaginado cdp = new ConsultasDePaginado();
        //Tomo el filtro y el valor para ejecutar consulta
        String filtroCant = filCant.getSelectedItem().toString();
        String valA = TxtBuscar1.getText();
        String valB = TxtBuscar2.getText();
        //Genero consulta para contar los registros
        String SSQL = cdp.paginarPorCant(filtroCant, valA, valB);
        //Paso el combo y el sql para que cuente los registros y pagine el JTable
        p.contarReg(cmbPag, SSQL);
        //Instancio llamada para ejecutar sql despues de contar los registro 
        //Debe de hacerse doble consulta para paginar un JTable
        this.llamadaV3 = 2;
        //llamo al evento en cmb para que me ejecute la consulta final con los limitadores
        this.cmbPagActionPerformed(evt);
        p.setJlabelPag(jLabel4, cmbPag);
    }//GEN-LAST:event_btnBuscarCantActionPerformed

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            getLogger(Vta.class.getName()).log(SEVERE, null, ex);
        }

        invokeLater(() -> {
            new Stok().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable Tabla2;
    private javax.swing.JComboBox TipoBusqueda;
    private javax.swing.JTextField TxtBuscar;
    private javax.swing.JTextField TxtBuscar1;
    private javax.swing.JTextField TxtBuscar2;
    public static javax.swing.JButton VolverM1;
    public static javax.swing.JButton VolverM2;
    public static javax.swing.JButton VolverM3;
    public static javax.swing.JButton VolverM4;
    private javax.swing.JButton botonPedido;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarFila;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarCant;
    private javax.swing.JButton btnBuscarProv;
    private javax.swing.JButton btnConfigStock;
    private javax.swing.JButton btnElimProv;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarFila;
    private javax.swing.JButton btnEliminarTodo;
    private javax.swing.JButton btnFilas;
    private javax.swing.JButton btnLimTbl;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiarTabla;
    private javax.swing.JButton btnModProv;
    private javax.swing.JButton btnModTabla;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnTruncate;
    public javax.swing.JButton btnrefrescartabla;
    private javax.swing.JComboBox cmbAlBa;
    private javax.swing.JComboBox<String> cmbFiltro;
    public javax.swing.JComboBox<String> cmbPag;
    private javax.swing.JComboBox filCant;
    private javax.swing.JLabel imglabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JButton modProduc;
    private javax.swing.JComboBox<String> nroFilas;
    private javax.swing.JTable tblAgregarProd;
    private javax.swing.JTable tblAgregarProv;
    private javax.swing.JTable tblProveedor;
    private javax.swing.JTable tblStockBajo;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtBuscarProv;
    // End of variables declaration//GEN-END:variables

}
