/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Control;

import Bienvenido.Menu;
import Bienvenido.RedesSociales;
import Bienvenido.Tesis;
import FNC.Funciones;
import coneccion.ControladorBackUpBD;
import coneccion.ModeloBackUp;
import static java.awt.EventQueue.invokeLater;
import static java.awt.event.KeyEvent.VK_ENTER;
import static java.awt.event.KeyEvent.VK_F1;
import static java.lang.Integer.parseInt;
import static java.lang.System.exit;
import static java.lang.System.out;
import static java.util.logging.Level.SEVERE;
import static java.util.logging.Logger.getLogger;
import javax.swing.ImageIcon;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.OK_OPTION;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import static javax.swing.JOptionPane.YES_OPTION;
import static javax.swing.JOptionPane.showConfirmDialog;
import static javax.swing.JOptionPane.showInternalMessageDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.UIManager.getInstalledLookAndFeels;
import static javax.swing.UIManager.setLookAndFeel;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Valentin
 */
public class Contro extends javax.swing.JFrame {

    public String U = null;
    public String P = null;
    public int ed = 0;
    public String sex = null;
    public int tipu = 0;
    public Object cambio = null;
    //Uso variable cambio para cambiar el combobox Admin = 1 y Empleado = 1

    //Val para el valor de busqueda de persona
    //fil para el filtro del select 
    public String val = null;
    public String fil = null;

    public Contro() {
        initComponents();
        VolverM.setMnemonic(VK_F1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        RUser = new javax.swing.JTextField();
        TipoU = new javax.swing.JComboBox<>();
        BotR = new javax.swing.JButton();
        RPass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        REdad = new javax.swing.JTextField();
        sexo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BotR1 = new javax.swing.JButton();
        VolverM = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        btnbuscar = new javax.swing.JButton();
        Txtbuscar = new javax.swing.JTextField();
        Btipo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        VolverM1 = new javax.swing.JButton();
        txtusuario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        seso = new javax.swing.JComboBox();
        txtedad = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnmod = new javax.swing.JButton();
        btnelimi = new javax.swing.JButton();
        btnborrar = new javax.swing.JButton();
        txtpass = new javax.swing.JPasswordField();
        bott2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        txtID = new javax.swing.JTextField();
        btnreestablecer = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        face = new javax.swing.JTextField();
        insta = new javax.swing.JTextField();
        twitt = new javax.swing.JTextField();
        btnModRedes = new javax.swing.JButton();
        btnResetRedes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        VolverM2 = new javax.swing.JButton();
        linkFacebook = new javax.swing.JTextField();
        linkInstagram = new javax.swing.JTextField();
        linkTwitter = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtGuardarBD = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        txtNomBD = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnBackUp = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtContra = new javax.swing.JPasswordField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtNomBDRec = new javax.swing.JTextField();
        txtContraRec = new javax.swing.JPasswordField();
        txtNomRec = new javax.swing.JTextField();
        txtURLrecuperar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btnRestoreBD = new javax.swing.JButton();
        VolverM3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(new ImageIcon(getClass().getResource("/Logo.png")).getImage());
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setDoubleBuffered(true);
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(600, 400));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(600, 500));

        panel1.setBackground(new java.awt.Color(100, 183, 100));
        panel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel1.setMinimumSize(new java.awt.Dimension(600, 500));
        panel1.setPreferredSize(new java.awt.Dimension(600, 500));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("User:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Password:");

        RUser.setToolTipText("Los usuarios se guardan en minuscula");
        RUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RUserKeyTyped(evt);
            }
        });

        TipoU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar:", "Admin", "Empleado" }));
        TipoU.setToolTipText("Seleccione tipos de permisos");
        TipoU.setAutoscrolls(true);
        TipoU.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TipoU.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TipoUItemStateChanged(evt);
            }
        });
        TipoU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoUActionPerformed(evt);
            }
        });

        BotR.setText("Registrar");
        BotR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotRMouseClicked(evt);
            }
        });
        BotR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotRActionPerformed(evt);
            }
        });
        BotR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BotRKeyPressed(evt);
            }
        });

        RPass.setToolTipText("Letras y numeros");
        RPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RPassKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Edad:");

        REdad.setToolTipText("Solo numeros");
        REdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REdadActionPerformed(evt);
            }
        });
        REdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                REdadKeyTyped(evt);
            }
        });

        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar:", "Masculino", "Femenino" }));
        sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Sexo:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Tipo de autorización:");

        BotR1.setText("Borrar campos");
        BotR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotR1ActionPerformed(evt);
            }
        });

        VolverM.setText("Volver Menu");
        VolverM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverMActionPerformed(evt);
            }
        });
        VolverM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VolverMKeyPressed(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo58x125.png"))); // NOI18N

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(BotR)
                        .addGap(193, 193, 193)
                        .addComponent(BotR1))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(420, 420, 420)
                        .addComponent(VolverM))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(RUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(REdad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RPass, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TipoU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(248, 248, 248))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TipoU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2)
                        .addGap(13, 13, 13)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(RUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(19, 19, 19)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(REdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(187, 187, 187)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotR)
                    .addComponent(BotR1))
                .addGap(24, 24, 24)
                .addComponent(VolverM))
        );

        jTabbedPane1.addTab("Registro usuarios", panel1);

        panel2.setBackground(new java.awt.Color(100, 183, 100));
        panel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel2.setMinimumSize(new java.awt.Dimension(500, 500));
        panel2.setPreferredSize(new java.awt.Dimension(600, 500));

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        Txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtbuscarKeyTyped(evt);
            }
        });

        Btipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Sexo" }));
        Btipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtipoActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Buscar por:");

        VolverM1.setText("Volver Menu");
        VolverM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverM1ActionPerformed(evt);
            }
        });
        VolverM1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VolverM1KeyPressed(evt);
            }
        });

        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText(" Usuario:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Edad:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Sexo:");

        seso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar:", "Masculino", "Femenino" }));
        seso.setToolTipText("");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Contraseña:");

        btnmod.setText("Modificar");
        btnmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodActionPerformed(evt);
            }
        });

        btnelimi.setText("Eliminar");
        btnelimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnelimiActionPerformed(evt);
            }
        });

        btnborrar.setText("Borrar campos");
        btnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarActionPerformed(evt);
            }
        });

        bott2.setText("Cerrar");
        bott2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bott2MouseClicked(evt);
            }
        });
        bott2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bott2ActionPerformed(evt);
            }
        });

        tabla.setAutoCreateRowSorter(true);
        tabla.getTableHeader().setReorderingAllowed(false);
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Usuario", "Contraseña", "Edad", "Sexo", "Tipo de usuario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabla.setEditingColumn(1);
        tabla.setEditingRow(1);
        tabla.getTableHeader().setReorderingAllowed(false);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setResizable(false);
            tabla.getColumnModel().getColumn(1).setResizable(false);
            tabla.getColumnModel().getColumn(2).setResizable(false);
            tabla.getColumnModel().getColumn(3).setResizable(false);
            tabla.getColumnModel().getColumn(4).setResizable(false);
            tabla.getColumnModel().getColumn(5).setResizable(false);
        }

        txtID.setVisible(false);

        btnreestablecer.setText("Eliminar registros usuarios");
        btnreestablecer.setToolTipText("Borra toda la tabla y deja user: admin pass: 1234");
        btnreestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreestablecerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)))
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel16)))
                        .addGap(18, 18, 18)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtpass, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtusuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtedad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addComponent(btnmod)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnelimi)
                            .addComponent(btnborrar)
                            .addComponent(bott2)))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(Btipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnbuscar))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                                .addComponent(btnreestablecer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(VolverM1)
                                .addGap(15, 15, 15)))))
                .addContainerGap(270, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(btnmod)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnelimi))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))))
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(seso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(10, 10, 10)
                        .addComponent(bott2))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnborrar)))
                .addGap(58, 58, 58)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Btipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VolverM1)
                    .addComponent(btnreestablecer))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar usuarios", panel2);

        jPanel2.setBackground(new java.awt.Color(100, 183, 100));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Link para red social Facebook : ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Link para red social Instagram : ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Link para red social Twitter : ");

        face.setEditable(false);
        face.setText("https://www.facebook.com/");
        face.setFocusable(false);
        face.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faceActionPerformed(evt);
            }
        });

        insta.setEditable(false);
        insta.setText("https://www.instagram.com/");
        insta.setFocusable(false);
        insta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instaActionPerformed(evt);
            }
        });

        twitt.setEditable(false);
        twitt.setText("https://twitter.com/");
        twitt.setFocusable(false);

        btnModRedes.setText("Modificar todas las redes");
        btnModRedes.setToolTipText("Modifica las redes a las paginas asignadas aqui");
        btnModRedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModRedesActionPerformed(evt);
            }
        });

        btnResetRedes.setText("Reset redes sociales");
        btnResetRedes.setToolTipText("Resetea las redes a las paginas principales");
        btnResetRedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetRedesActionPerformed(evt);
            }
        });

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(212, 208, 200));
        jTextPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextPane1.setText("Para asignar una página a cada uno de los links, escribir lo que se encuentra luego de la \" / \".\n\nEjemplo face: https://www.facebook.com/NombreDeTuPagina\nEjemplo insta: https://www.instagram.com/NombrDeTuPagina\nEjemplo twitter: https://twitter.com/NombrDeTuPagina\n"); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        VolverM2.setText("Volver Menu");
        VolverM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverM2ActionPerformed(evt);
            }
        });
        VolverM2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VolverM2KeyPressed(evt);
            }
        });

        linkFacebook.setText("NombreDeTuPagina");
        linkFacebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkFacebookActionPerformed(evt);
            }
        });

        linkInstagram.setText("NombreDeTuPagina");

        linkTwitter.setText("NombreDeTuPagina");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnModRedes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnResetRedes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(twitt, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(face, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(linkTwitter)
                            .addComponent(linkInstagram)
                            .addComponent(linkFacebook)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(VolverM2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(linkFacebook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(face, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(linkInstagram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(linkTwitter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(twitt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(insta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnModRedes)
                        .addGap(33, 33, 33)
                        .addComponent(btnResetRedes)))
                .addGap(34, 34, 34)
                .addComponent(VolverM2)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar Redes Sociales", jPanel2);

        jPanel3.setBackground(new java.awt.Color(100, 183, 100));
        jPanel3.setMinimumSize(new java.awt.Dimension(756, 571));

        txtGuardarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGuardarBDActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Inserte URL ubicacion mysqldump");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Inserte Usuario de la BD");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Inserte Contraseña de la BD");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Inserte el Nombre tabla BD");

        btnBackUp.setText("BackUpBD");
        btnBackUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackUpActionPerformed(evt);
            }
        });

        jButton1.setText("Examinar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Inserte URL ubicacion mysql");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Inserte Usuario de la BD");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Inserte Contraseña de la BD");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Inserte el Nombre tabla BD");

        txtURLrecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtURLrecuperarActionPerformed(evt);
            }
        });

        jButton2.setText("Examinar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnRestoreBD.setText("RestoreBD");
        btnRestoreBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestoreBDActionPerformed(evt);
            }
        });

        VolverM3.setText("Volver Menu");
        VolverM3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverM3ActionPerformed(evt);
            }
        });
        VolverM3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VolverM3KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(btnBackUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(343, 343, 343))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtNomBD, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtContra, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtGuardarBD, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addGap(12, 12, 12))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(btnRestoreBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(190, 190, 190)
                        .addComponent(VolverM3)
                        .addGap(46, 46, 46))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(txtNomBDRec, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtURLrecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtContraRec, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNomRec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGuardarBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addComponent(btnBackUp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtURLrecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtContraRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomBDRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRestoreBD, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VolverM3))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BackUpBD", jPanel3);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void linkFacebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkFacebookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linkFacebookActionPerformed

    private void VolverM2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VolverM2KeyPressed
        // TODO add your handling code here:
        char carr = (char) evt.getKeyCode();
        if (carr == VK_F1) {
            Menu men = new Menu();
            men.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_VolverM2KeyPressed

    private void VolverM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverM2ActionPerformed
        // TODO add your handling code here:
        Menu men = new Menu();
        men.setVisible(true);
        dispose();
    }//GEN-LAST:event_VolverM2ActionPerformed

    private void btnResetRedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetRedesActionPerformed
        // TODO add your handling code here:
        //Abro pregunta para ver si quiere o no resetear las redes , resp si entra resp no sale
        int resp = showConfirmDialog(null, "¿Está seguro de querer borrar las redes sociales ya guardadas?", "PREGUNTA", QUESTION_MESSAGE);
        if (resp == OK_OPTION) {
            RedesSociales rs = new RedesSociales();
            rs.resetRedes();
            showMessageDialog(null, "¡Las redes se resetearon satisfactoriamente! ", "INFORMACIÓN", INFORMATION_MESSAGE);
        } else {
            showMessageDialog(null, "¡Las redes no fueron reseteadas! ", "INFORMACIÓN", INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnResetRedesActionPerformed

    private void btnModRedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModRedesActionPerformed
        //Obtengo lo escrito en la modificacion de redes sociales al presionar el boton modificar
        String face = "";
        String insta = "";
        String twitt = "";
        face = linkFacebook.getText();
        insta = linkInstagram.getText();
        twitt = linkTwitter.getText();
        //Lllamo al paquete  RedesSociales y dentro de este al metodo modRedes que modifica las redes
        //Abro pregunta para ver si quiere o no modificar las redes , resp si entra resp no sale
        int resp = showConfirmDialog(null, "¿Quiere modificar las redes ya guardadas?", "PREGUNTA", YES_NO_OPTION);
        if (resp == OK_OPTION) {
            RedesSociales red = new RedesSociales();
            red.modRedes(face, insta, twitt);
        }
    }//GEN-LAST:event_btnModRedesActionPerformed

    private void instaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_instaActionPerformed

    private void faceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faceActionPerformed

    private void btnreestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreestablecerActionPerformed

        ConsultaControl consulta = new ConsultaControl();
        int s = showConfirmDialog(null, "Esta seguro que desea borrar todos los registros de la tabla usuarios.\nSe creara un usuario y contraseña por defecto.\n"
            + "Usuario: admin\nContrseña: 1234", "Advertencia", WARNING_MESSAGE);

        if (s == YES_OPTION) {
            consulta.reestablecer_tabla();
        } else {
            showMessageDialog(null, " Registros no borrados ");
        }
    }//GEN-LAST:event_btnreestablecerActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
        // cargo los datos de la tabla en los jtexfields
        try {
            int Selectfila = 0;
            Selectfila = tabla.getSelectedRow();
            if (Selectfila == -1) {
                showMessageDialog(null, "No a seleccionado ninguna fila a modificar", "Error", ERROR_MESSAGE);
            } else {
                DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();

                String id = (String) modelo.getValueAt(Selectfila, 0);

                String user = (String) modelo.getValueAt(Selectfila, 1);
                String pas = (String) modelo.getValueAt(Selectfila, 2);
                String edad = (String) modelo.getValueAt(Selectfila, 3);
                Object sexxo = modelo.getValueAt(Selectfila, 4);

                out.println("ID es ahora = " + id);
                txtID.setText(id);
                txtusuario.setText(user);
                txtpass.setText(pas);
                txtedad.setText(edad);
                seso.setSelectedItem(sexxo);

            }
        } catch (Exception e) {
            showMessageDialog(null, "Error " + e + " Intentelo de nuevo", "Error", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tablaMouseClicked

    private void bott2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bott2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bott2ActionPerformed

    private void bott2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bott2MouseClicked
        // TODO add your handling code here:
        exit(0);
    }//GEN-LAST:event_bott2MouseClicked

    private void btnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarActionPerformed
        // TODO add your handling code here:
        Funciones fun = new Funciones();
        fun.limpiar_texto(panel2);
        fun.cmbCambiarseleccion(sexo);
    }//GEN-LAST:event_btnborrarActionPerformed

    private void btnelimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnelimiActionPerformed
        // TODO add your handling code here:
        ConsultaControl con = new ConsultaControl();
        if (txtID.getText().isEmpty()) {
            showMessageDialog(null, "No hay datos para eliminar.\n"
                + "Por favor, seleccione un registro de la tabla.", "Error en la operación", ERROR_MESSAGE);
        } else {
            int idd = parseInt(txtID.getText());
            con.Eliminar(idd);
        }
    }//GEN-LAST:event_btnelimiActionPerformed

    private void btnmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodActionPerformed
        // TODO add your handling code here:
        ConsultaControl consul = new ConsultaControl();
        if (txtID.getText().isEmpty()) {
            showMessageDialog(null, "No hay datos para modificar.\n"
                + "Por favor, seleccione un registro de la tabla.", "Error en la operación", ERROR_MESSAGE);

        } else {
            Object se = seso.getSelectedItem().toString();

            consul.modificardatos(txtusuario.getText(), new String(txtpass.getPassword()), txtedad.getText(), (String) se, txtID.getText());
        }
    }//GEN-LAST:event_btnmodActionPerformed

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void VolverM1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VolverM1KeyPressed
        // TODO add your handling code here:
        char carr = (char) evt.getKeyCode();
        if (carr == VK_F1) {
            Menu men = new Menu();
            men.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_VolverM1KeyPressed

    private void VolverM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverM1ActionPerformed
        // TODO add your handling code here:
        Menu men = new Menu();
        men.setVisible(true);
        dispose();
    }//GEN-LAST:event_VolverM1ActionPerformed

    private void BtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtipoActionPerformed

    private void TxtbuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtbuscarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtbuscarKeyTyped

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed

        ConsultaControl conns = new ConsultaControl();
        val = Txtbuscar.getText();
        fil = Btipo.getSelectedItem().toString();
        conns.buscar1(fil, val, tabla);
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void VolverMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VolverMKeyPressed
        // TODO add your handling code here:
        char carr = (char) evt.getKeyCode();
        if (carr == VK_F1) {
            Menu men = new Menu();
            men.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_VolverMKeyPressed

    private void VolverMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverMActionPerformed
        // TODO add your handling code here:
        Menu men = new Menu();
        men.setVisible(true);
        dispose();
    }//GEN-LAST:event_VolverMActionPerformed

    private void BotR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotR1ActionPerformed
        // TODO add your handling code here:
        Funciones fun = new Funciones();
        fun.limpiar_texto(panel1);
    }//GEN-LAST:event_BotR1ActionPerformed

    private void sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoActionPerformed

    private void REdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_REdadKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c == VK_ENTER) {
            BotR.doClick();
        }
        // Valida solo letras y numero el contenido de abajo en los campos
        //de textos.
        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_REdadKeyTyped

    private void REdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REdadActionPerformed

    private void RPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RPassKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c == VK_ENTER) {
            BotR.doClick();
        }
        // Valida solo letras y numero el contenido de abajo en los campos
        //de textos.
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c
            < '0' || c > '9')) {
        evt.consume();
        }
    }//GEN-LAST:event_RPassKeyTyped

    private void BotRKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BotRKeyPressed
        // TODO add your handling code here:
        char car = (char) evt.getKeyCode();
        if (car == VK_ENTER) {
            BotR.doClick();
        }
    }//GEN-LAST:event_BotRKeyPressed

    private void BotRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotRActionPerformed
        // TODO add your handling code here:
        ConsultaControl con = new ConsultaControl();

        U = RUser.getText();//usuario
        P = new String(RPass.getPassword());//password
        ed = parseInt(REdad.getText());//edad
        sex = sexo.getSelectedItem().toString();//tipo de sexo
        cambio = TipoU.getSelectedItem();//Tipo de usuario
        out.println("Cambio ahora es el numero : " + cambio);
        //Verifico si el usuario es admin o empleado
        if ((cambio.equals("Admin")) && (cambio != "Seleccionar:")) {
            tipu = 1;
        } else if ((cambio.equals("Empleado")) && (cambio != "Seleccionar:")) {
            tipu = 2;
        } else {
            showInternalMessageDialog(null, "Seleccione un tipo de usuario", "Error", ERROR_MESSAGE);
        }
        out.println("tipu es ahora = " + tipu);
        //Verifico si se llenaron todos los campos
        if ((U.isEmpty()) || (P.isEmpty()) || (ed == 0)) {
            showMessageDialog(null, "Debe rellenar todos los campos", "Error", ERROR_MESSAGE);
        } else {
            U = U.toLowerCase();
            P = P.toLowerCase();
            //Envio el nombre de usuario para verificar si existe en la BD
            boolean a = con.verificarUserBD(U);
            //Si existe pide un nombre distinto, si no registra el nuevo usuario
            if (a == true) {
                showMessageDialog(null, "El nombre de usuario ya existe en la BD por favor elija otro", "INFORMACION", INFORMATION_MESSAGE);
            } else {
                //paso parametros para insertar nuevo registro
                con.InsertarDatos(U, P, ed, sex, tipu);
            }
        }
    }//GEN-LAST:event_BotRActionPerformed

    private void BotRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotRMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BotRMouseClicked

    private void TipoUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoUActionPerformed

    private void TipoUItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TipoUItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoUItemStateChanged

    private void RUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RUserKeyTyped
        // TODO add your handling code here:
        // el usuario y contraseña al darle enter haga focus en aceptar para
        //pasar a la pagina siguiente !
        char c = evt.getKeyChar();
        if (c == VK_ENTER) {
            BotR.doClick();
        }
        // Valida solo letras y numero el contenido de abajo en los campos
        //de textos.
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c
            < '0' || c > '9')) {
        evt.consume();
        }
    }//GEN-LAST:event_RUserKeyTyped

    private void txtGuardarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuardarBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGuardarBDActionPerformed

    private void btnBackUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackUpActionPerformed
        ModeloBackUp mod = new ModeloBackUp();
        mod.setUrlGuardado(txtGuardarBD.getText()); 
        mod.setUsuario(txtNom.getText());
        mod.setContra(String.valueOf(txtContra.getPassword())); 
        mod.setNomBD(txtNomBD.getText());
        ControladorBackUpBD con = new ControladorBackUpBD();
        con.backUP();
        txtGuardarBD.setText("");
        txtNom.setText("");
        txtNomBD.setText("");
        txtContra.setText("");
     
    }//GEN-LAST:event_btnBackUpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     Funciones fun = new Funciones();
     String ur = "";
     
     txtGuardarBD.setText(fun.buscarDir(ur));
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtURLrecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtURLrecuperarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtURLrecuperarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     Funciones fun = new Funciones();
     String ur = "";
     
     txtURLrecuperar.setText(fun.buscarDir(ur));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnRestoreBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestoreBDActionPerformed
        ModeloBackUp mod = new ModeloBackUp();
        mod.setUrlRecuperar(txtURLrecuperar.getText()); 
        mod.setUsuario(txtNomRec.getText());
        mod.setContra(String.valueOf(txtContraRec.getPassword())); 
        mod.setNomRecuperarBD(txtNomBDRec.getText());
        ControladorBackUpBD con = new ControladorBackUpBD();
        con.restore();
        txtURLrecuperar.setText("");
        txtNomRec.setText("");
        txtNomBDRec.setText("");
        txtContraRec.setText("");
     
    }//GEN-LAST:event_btnRestoreBDActionPerformed

    private void VolverM3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverM3ActionPerformed
       Menu men = new Menu();
        men.setVisible(true);
        dispose();
    }//GEN-LAST:event_VolverM3ActionPerformed

    private void VolverM3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VolverM3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_VolverM3KeyPressed

    public static void main(String[] args) throws ClassNotFoundException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        for (javax.swing.UIManager.LookAndFeelInfo info : getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                try {
                    setLookAndFeel(info.getClassName());
                } catch (InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    getLogger(Tesis.class.getName()).log(SEVERE, null, ex);
                }
                break;
            }
        }

        //</editor-fold>

        /* Create and display the form */
        invokeLater(() -> {
            new Contro().setVisible(true);
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton BotR;
    public static javax.swing.JButton BotR1;
    private javax.swing.JComboBox<String> Btipo;
    private javax.swing.JTextField REdad;
    private javax.swing.JPasswordField RPass;
    private javax.swing.JTextField RUser;
    private javax.swing.JComboBox<String> TipoU;
    private javax.swing.JTextField Txtbuscar;
    public static javax.swing.JButton VolverM;
    public static javax.swing.JButton VolverM1;
    public static javax.swing.JButton VolverM2;
    public static javax.swing.JButton VolverM3;
    private javax.swing.JButton bott2;
    private javax.swing.JButton btnBackUp;
    private javax.swing.JButton btnModRedes;
    private javax.swing.JButton btnResetRedes;
    private javax.swing.JButton btnRestoreBD;
    private javax.swing.JButton btnborrar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnelimi;
    private javax.swing.JButton btnmod;
    private javax.swing.JButton btnreestablecer;
    public static javax.swing.JTextField face;
    public static javax.swing.JTextField insta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField linkFacebook;
    private javax.swing.JTextField linkInstagram;
    private javax.swing.JTextField linkTwitter;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JComboBox seso;
    private javax.swing.JComboBox<String> sexo;
    private javax.swing.JTable tabla;
    public static javax.swing.JTextField twitt;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JPasswordField txtContraRec;
    private javax.swing.JTextField txtGuardarBD;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtNomBD;
    private javax.swing.JTextField txtNomBDRec;
    private javax.swing.JTextField txtNomRec;
    private javax.swing.JTextField txtURLrecuperar;
    private javax.swing.JTextField txtedad;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
