/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bienvenido;

import Control.Contro;
import Stock.Stok;
import Venta.Vta;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Valentin
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    // Tipos de usuarios en la BD son 1 = Administrados; 2 = Empleado.
    // Para crear nuevos usuarios debe implementarlo el desarrollador no se creo metodo via programa.
    ConsultaInicioSesion ini = new ConsultaInicioSesion();

    public Menu() {
        initComponents();
        //Traigo el tipo de usuario con ini.guardar(); ini es la variable de 
        //ConsultaInicioSesion y guardar() es el metodo donde guardo el usuario
        String user = ini.guardar();
        if (user.equals("2")) {
            control.setVisible(false);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inicio = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        btnTwitt = new javax.swing.JButton();
        venta = new javax.swing.JButton();
        stok = new javax.swing.JButton();
        control = new javax.swing.JButton();
        btnFace = new javax.swing.JButton();
        btnInsta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setIconImage(new ImageIcon(getClass().getResource("/Logo.png")).getImage());
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 500));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 500));
        jPanel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        inicio.setText("Cerrar sesión");
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });

        lbl1.setBackground(new java.awt.Color(204, 204, 255));
        lbl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl1.setForeground(new java.awt.Color(0, 153, 255));
        lbl1.setText("Sesion: Administrador");
        lbl1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbl1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lbl1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btnTwitt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/twitter.png"))); // NOI18N
        btnTwitt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTwitt.setBorderPainted(false);
        btnTwitt.setContentAreaFilled(false);
        btnTwitt.setFocusPainted(false);
        btnTwitt.setMaximumSize(new java.awt.Dimension(60, 60));
        btnTwitt.setMinimumSize(new java.awt.Dimension(60, 60));
        btnTwitt.setPreferredSize(new java.awt.Dimension(62, 62));
        btnTwitt.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/twitterpress.png"))); // NOI18N
        btnTwitt.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/twitter.png"))); // NOI18N
        btnTwitt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwittActionPerformed(evt);
            }
        });

        venta.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sales.png"))); // NOI18N
        venta.setText("Ventas");
        venta.setBorder(null);
        venta.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        venta.setIconTextGap(0);
        venta.setMargin(new java.awt.Insets(4, 4, 4, 4));
        venta.setMaximumSize(new java.awt.Dimension(131, 61));
        venta.setMinimumSize(new java.awt.Dimension(131, 61));
        venta.setPreferredSize(new java.awt.Dimension(131, 61));
        venta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salespress.png"))); // NOI18N
        venta.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ventaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventaActionPerformed(evt);
            }
        });

        stok.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        stok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock_folder_propertiesnopress.png"))); // NOI18N
        stok.setText("Control Stock");
        stok.setBorder(null);
        stok.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        stok.setMargin(new java.awt.Insets(4, 4, 4, 4));
        stok.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/stock_folder_properties.png"))); // NOI18N
        stok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stokActionPerformed(evt);
            }
        });

        control.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        control.setIcon(new javax.swing.ImageIcon(getClass().getResource("/control_panel_wcorrecto.png"))); // NOI18N
        control.setText("Control");
        control.setBorder(null);
        control.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        control.setMargin(new java.awt.Insets(4, 4, 4, 4));
        control.setMaximumSize(new java.awt.Dimension(131, 61));
        control.setMinimumSize(new java.awt.Dimension(131, 61));
        control.setPreferredSize(new java.awt.Dimension(131, 61));
        control.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/control_panel_w.png"))); // NOI18N
        control.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                controlAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        control.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controlActionPerformed(evt);
            }
        });

        btnFace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/facebook.png"))); // NOI18N
        btnFace.setBorder(null);
        btnFace.setBorderPainted(false);
        btnFace.setContentAreaFilled(false);
        btnFace.setFocusPainted(false);
        btnFace.setName(""); // NOI18N
        btnFace.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/facebookpress.png"))); // NOI18N
        btnFace.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/facebook.png"))); // NOI18N
        btnFace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFaceActionPerformed(evt);
            }
        });

        btnInsta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instagram.png"))); // NOI18N
        btnInsta.setBorder(null);
        btnInsta.setBorderPainted(false);
        btnInsta.setContentAreaFilled(false);
        btnInsta.setFocusPainted(false);
        btnInsta.setMaximumSize(new java.awt.Dimension(60, 60));
        btnInsta.setMinimumSize(new java.awt.Dimension(60, 60));
        btnInsta.setName(""); // NOI18N
        btnInsta.setPreferredSize(new java.awt.Dimension(62, 62));
        btnInsta.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/instagrampress.png"))); // NOI18N
        btnInsta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/instagram.png"))); // NOI18N
        btnInsta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstaActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                .addGap(1, 1, 1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER, false)
                            .addComponent(stok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(control, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(venta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnFace, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnInsta, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTwitt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(227, 227, 227)
                        .addComponent(inicio)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(venta, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(stok, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(control, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(inicio)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFace, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTwitt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInsta, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
        // TODO add your handling code here:
        Inicio_Sesion ini = new Inicio_Sesion();
        ini.setVisible(true);
        dispose();
    }//GEN-LAST:event_inicioActionPerformed

    private void jPanel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel1AncestorAdded

    }//GEN-LAST:event_jPanel1AncestorAdded

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_formComponentShown

    private void lbl1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lbl1AncestorAdded
        // TODO add your handling code here:
//Metodo guardar guarda el tipo de usuario que ha ingresado en la sesión
        String user = ini.guardar();
//Creo un if para transformar el 1 y 2 de base de datos en admin y empleado
        if (user.equals("1")) {
            lbl1.setText("Sesión: Administrador " + "Usuario: " + ini.getUsuario());
            System.out.println("Soy admin");
        } else if (user.equals("2")) {
            lbl1.setText("Sesión: Empleado " + "Usuario: " + ini.getUsuario());
            System.out.println("Soy empleado");
        }
    }//GEN-LAST:event_lbl1AncestorAdded

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:

    }//GEN-LAST:event_formComponentHidden

    private void ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventaActionPerformed
        // TODO add your handling code here:
        Vta vt = new Vta();
        vt.setVisible(true);
        dispose();
    }//GEN-LAST:event_ventaActionPerformed

    private void stokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stokActionPerformed
        // TODO add your handling code here:
        Stok sto = new Stok();
        sto.setVisible(true);
        dispose();
    }//GEN-LAST:event_stokActionPerformed

    private void controlAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_controlAncestorAdded
        // TODO add your handling code here:
        ConsultaInicioSesion ini = new ConsultaInicioSesion();
        String user = ini.guardar();
        //Verifico que el usuario sea admin . si no es admin entonces las funciones de controles no estan 
        //habilitadas para su uso
        if (user.equals("2")) {
            control.setVisible(false);
            System.out.println("Tus funciones como empleado en el panel son limitadas");
        }
    }//GEN-LAST:event_controlAncestorAdded

    private void controlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controlActionPerformed
        // TODO add your handling code here:
        Contro contrr = new Contro();
        contrr.setVisible(true);
        dispose();
    }//GEN-LAST:event_controlActionPerformed

    private void btnFaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFaceActionPerformed
        try {
            // TODO add your handling code here:
            //Desktop permite obtener archivos de mi escritorio o abrir programas . en este caso
            //uso getdesktop().browse para abrir el navegador por defecto y dirigirme a la url indicada
            Desktop enlace = Desktop.getDesktop();
            enlace.browse(new URI(RedesSociales.getFace()));
        } catch (URISyntaxException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFaceActionPerformed

    private void btnInstaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstaActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            //Desktop permite obtener archivos de mi escritorio o abrir programas . en este caso
            //uso getdesktop().browse para abrir el navegador por defecto y dirigirme a la url indicada
            Desktop.getDesktop().browse(new URI(RedesSociales.getInsta()));
        } catch (URISyntaxException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInstaActionPerformed

    private void btnTwittActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwittActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            //Desktop permite obtener archivos de mi escritorio o abrir programas . en este caso
            //uso getdesktop().browse para abrir el navegador por defecto y dirigirme a la url indicada
            Desktop.getDesktop().browse(new URI(RedesSociales.getTwitt()));
        } catch (URISyntaxException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTwittActionPerformed

    private void ventaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ventaAncestorAdded

    }//GEN-LAST:event_ventaAncestorAdded

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFace;
    private javax.swing.JButton btnInsta;
    private javax.swing.JButton btnTwitt;
    private javax.swing.JButton control;
    private javax.swing.JButton inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lbl1;
    private javax.swing.JButton stok;
    private javax.swing.JButton venta;
    // End of variables declaration//GEN-END:variables
}
